
pipeline:
  steps:
    - name: scaler
      class: MinMaxScaler
    - name: iso_forest
      class: IsolationForest
      params:
        random_state: 42
        # contamination: 0.1

param_grid:
  iso_forest__n_estimators: [100, 200, 300, 400, 500]
  iso_forest__contamination: [0.01, 0.05, 0.1]
  iso_forest__max_samples: ['auto']
  iso_forest__max_features: [1, 0.5, 'auto']